### ISSUE TITLE
Optional type parameter

### ISSUE THREAD

**Issue by flavienaudin** [novaway/elasticsearch-client#45]
https://github.com/novaway/elasticsearch-client/blob/c7bda2c99b511f7dfd4fcb5fa4b08fab6ac9f9b6/src/QueryExecutor.php#L28-L34

Do you think the parameter $type could be optional in order to make search over multiple types of document ? Or do you have another way to do such kind of search ?

**Comment by CheapHasz** [comment]
From the `ElasticSearch\Client::search` phpdoc : 
`['type']                     = (list) A comma-separated list of document types to search; leave empty to perform the operation on all types`

Therefore, it should be possible to pass multiple types, comma-separated, to search on multiple types.
Have you tried that ?

**Comment by flavienaudin** [comment]
It's working. I missed the first part of this documentation.
Thank you for the tip.
